In [1]:
print("Hello, DataSense!")

Hello, DataSense!

In [2]:
print("Welcome to Python for Data Analytics")
print("Day 1: Python Fundamentals")

Welcome to Python for Data Analytics
Day 1: Python Fundamentals

In [3]:
print(15)

15

In [4]:
print(20 + 5)

25

In [5]:
print("Hello" + "Juan")

HelloJuan

In [6]:
print("5" + " Apples")

5 Apples

In [7]:
print("20" + "5")

205

In [10]:
"""
Quantity is declared as 12
and that the unit price
is 350. So, the revenue is 4,200.
"""
# Calculate monthly revenue
quantity = 12
unit_price = 350
revenue = quantity * unit_price

print(revenue)

4200

In [11]:
product = "Laptop"
quantity = 4
unit_price = 35000

revenue = quantity * unit_price
print(revenue)

140000

In [12]:
this_is_my_variable = True

In [13]:
this_is_my_variable = "Juan de la Cruz"

In [14]:
this_is_my_variable

'Juan de la Cruz'

In [15]:
Varname = "Juan"

In [16]:
varname = "Pedro"

In [17]:
Varname

'Juan'

In [18]:
varname

'Pedro'

In [1]:
product = "Laptop" # str
quantity = 4 # int
price = 35000.50 # float
available = True # bool
remarks = None # no value yet

for variable in [product, quantity, price, available, remarks]:
    print(type(variable))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'NoneType'>

In [23]:
quantity = 10
unit_price = 250
unit_cost = 180

revenue = quantity * unit_price
total_cost = quantity * unit_cost
profit = revenue - total_cost

print(profit)

700

In [31]:
# f string
print(f"Revenue: {revenue}; Total Cost: {total_cost}; Profit: {revenue - total_cost}")

Revenue: 2500; Total Cost: 1800; Profit: 700

In [32]:
# \n for new line
print(f"Revenue: {revenue}", end="\n")
print(f"Total Cost: {total_cost}", end="\n")
print(f"Profit: {revenue - total_cost}", end="\n")

Revenue: 2500
Total Cost: 1800
Profit: 700

In [33]:
# \t for tab
print(f"Revenue: {revenue}", end="\t")
print(f"Total Cost: {total_cost}", end="\t")
print(f"Profit: {revenue - total_cost}", end="\t")

Revenue: 2500	Total Cost: 1800	Profit: 700

In [34]:
# ++
print(f"Revenue: {revenue}; Total Cost: {total_cost}; Profit: {revenue - total_cost}", end="++")

Revenue: 2500; Total Cost: 1800; Profit: 700++

In [37]:
# type conversion
price_text = "35000"
qty_text = "4"

price = float(price_text)
quantity = int(qty_text)

revenue = price * quantity
print(revenue)

140000.0

In [36]:
float(price_text) + int(qty_text)

35004.0

In [39]:
int(price_text) / 23

1521.7391304347825

In [40]:
int(price_text) // 23

1521

In [41]:
f"{int(price_text) / 23:.2f}"

'1521.74'

In [43]:
sales = 12000
target = 10000

print(sales >= target)
print(sales == target)
print(sales != target)

True
False
True

In [47]:
# XOR operator
5 ^ 3

6

In [55]:
# exponentiation
5 ** 3

125

In [48]:
payment = "Cash"

In [49]:
payment == "Cash" and payment == "Card"

False

In [50]:
(payment == "Cash" or payment == "Card") and payment == "GCash"

False

In [63]:
score = 79

In [64]:
if score >= 90:
    rating = "Excellent"
elif score >= 80 and score < 90:
    rating = "Very Good"
elif score >= 70 and score < 80:
    rating = "Good"
else:
    rating = "Needs Improvement"

print(rating)

Good

In [83]:
product = "Laptop"
qty = 4
unit_price = 35000
unit_cost = 28000

revenue = qty * unit_price
cost = qty * unit_cost
profit = revenue - cost
margin = profit / revenue * 100

In [67]:
print(margin)

20.0

In [84]:
if margin >= 20:
    condition = "healthy"
else:
    condition = "not healthy"

print(condition)

healthy

In [89]:
print(f"The profit margin has been found to be {condition} — considering the profit at PHP {profit:,.2f} reaching at least 20% of the revenue at PHP {revenue:,.2f}.")

The profit margin has been found to be healthy — considering the profit at PHP 28,000.00 reaching at least 20% of the revenue at PHP 140,000.00.

In [5]:
# Day 2 warm-up
product = "Laptop"
quantity = 4
unit_price = 35000
unit_cost = 28000
revenue = quantity * unit_price
cost = quantity * unit_cost
profit = revenue - cost
margin = profit / revenue * 100
print(f"Profit: {profit}")
print(f"Margin: {margin:.2f}%")
if margin >= 20:
    print("Healthy margin")
else:
    print("Needs review")

Profit: 28000
Margin: 20.00%
Healthy margin

In [6]:
student_name = "Angela"
final_grade = 82

In [8]:
if final_grade >= 75:
    print(f"{student_name} passed")
else:
    print(f"{student_name} failed")

Angela passed

In [9]:
employee = "Mark"
monthly_sales = 87000

In [11]:
if monthly_sales >= 100000:
    print(f"{employee} generated excellent monthly sales.")
elif monthly_sales >= 75000 and monthly_sales < 100000:
    print(f"{employee} generated good monthly sales.")
elif monthly_sales >= 50000 and monthly_sales < 75000:
    print(f"{employee} generated average monthly sales.")
else:
    print(f"{employee} generated poor monthly sales.")

Mark generated good monthly sales.

In [12]:
sales = 90000
profit = 15000
is_active = True

In [13]:
if sales >= 75000 and profit > 0:
    print("Good and profitable.")
if not is_active:
    print("Account is inactive.")

Good and profitable.

In [15]:
employee = "Carla"
monthly_sales = 125000
customer_rating = 4.6
attendance_rate = 96
disciplinary_action = True

In [19]:
if monthly_sales >= 120000 and customer_rating >= 4.5 and attendance_rate >= 95 and disciplinary_action == False:
    print("Outstanding")
elif monthly_sales >= 90000 and customer_rating >= 4.0 and attendance_rate >= 90:
    print("Very good") 
elif monthly_sales > 60000 and attendance_rate >= 85:
    print("Satisfactory") 
else:
    print("Needs improvement; ineligible for incentive")

Very good

In [62]:
# lists use brackets
sales = [45000, 82000, 120000, 67000]
print(sales[0]) # first item
print(len(sales)) # number of items
print(sum(sales)) # total sales
print(max(sales)) # highest value

45000
4
314000
120000

In [21]:
sales = [45000, 82000, 120000, 67000, 95000]
print(sales[0]) # first item: 45000
print(sales[2]) # third item: 120000
print(sales[-1]) # last item: 95000
print(sales[1:4]) # items from index 1 to 3
print(sales[:3]) # first three items
print(sales[3:]) # from index 3 to the end

45000
120000
95000
[82000, 120000, 67000]
[45000, 82000, 120000]
[67000, 95000]

In [25]:
sales[0:4:2] # even numbers

[45000, 120000]

In [23]:
myList = ["Ally",34,True]

In [26]:
type(myList[2]) # variable type

bool

In [27]:
len(myList)

3

In [29]:
min(sales)

45000

In [30]:
max(sales)

120000

In [56]:
# learn append and remove methods (see below)

In [39]:
matrix_A = [
    [1,2],
    [2,3]
    ]

In [40]:
matrix_A[1]

[2, 3]

In [41]:
matrix_A[1][1]

3

In [44]:
matrix_B = [
    [1,2,3,4],
    [5,6,7],
    8,
    [9,10,[11,12,13],14],
    [15,[16,17,[18,19,20]],21]
    ]
# retrieve 19 from matrix_B

In [45]:
matrix_B[4][1][2][1]

19

In [50]:
# learn pop method

In [51]:
# learn list.sort and sorted methods

In [52]:
regions = ["North","South","North","Central","North"]

In [53]:
regions.count("North")

3

In [54]:
regions.index("North")

0

In [55]:
regions[3]

'Central'

In [57]:
# learn append and remove methods
sales = [45000, 82000, 120000]
sales.append(67000)
sales.remove(45000)
average = sum(sales) / len(sales)
print(f"Average sales: {average:.2f}")

Average sales: 89666.67

In [63]:
# tuples use parentheses
coordinates = (9.78, 125.49)
latitude = coordinates[0]
longitude = coordinates[1]
print(latitude)
print(longitude)

9.78
125.49

In [68]:
# dictionaries
product = {
    "name": "Laptop",
    "category": "Electronics",
    "price": 35000,
    "stock": 20,
    "active": True
}

print(product["name"])
print(product["price"])

product["stock"] = 18 # the item of a key is mutable

# "name" is a key, "Laptop" is a value, "name": "Laptop" is an item, and product = {...} is a dictionary

Laptop
35000

In [70]:
# sets
categories = {"Laptop", "Phone", "Tablet", "Phone"}

print(categories)
print("Laptop" in categories)

unique_regions = set(["North", "South", "North"])

print(unique_regions)
print("East" in unique_regions)

{'Laptop', 'Tablet', 'Phone'}
True
{'North', 'South'}
False

In [73]:
set(categories)

{'Laptop', 'Phone', 'Tablet'}

In [74]:
set(unique_regions)

{'North', 'South'}

In [75]:
a = {"A","B","C"}
b = {"A","C"}

In [81]:
a & b # intersection

{'A', 'C'}

In [82]:
a - b # difference

{'B'}

In [83]:
a | b # union

{'A', 'B', 'C'}

In [88]:
# for loops
sales = [45000, 82000, 120000, 67000]

total = 0

for value in sales:
    total = total + value
    print(value) # 0 => 245,000 => 112,0000 => 194,000 => 314,000

print(f"Total: {total}")

45000
82000
120000
67000
Total: 314000

In [85]:
for num in range(1,11):
    print(num)

1
2
3
4
5
6
7
8
9
10

In [91]:
# combining loops and conditions
sales = [45000, 82000, 120000, 67000, 95000]

high_count = 0

for amount in sales:
    if amount >= 100000:
        label = "Excellent"
        high_count += 1
    elif amount >= 75000:
        label = "Good"
    else:
        label = "Needs review"

print(amount, label)
print(f"Excellent records: {high_count}")

95000 Good
Excellent records: 1

In [92]:
# while loops
count = 1

while count <= 5:
    print(f"Attempt {count}")
    count += 1

print("Loop finished")

Attempt 1
Attempt 2
Attempt 3
Attempt 4
Attempt 5
Loop finished

In [94]:
# the break statement ends a while loop
count = 0

while True:
    count += 1
    if count == 3:
        break
        
print(count)

3

In [98]:
# the continue statement enables skipping
count = 0

while count < 5:
    count += 1
    if count == 3:
        continue
    print(count)

1
2
4
5

In [103]:
# functions
def calculate_profit(revenue, cost): # calculate_profit is a function, whereas revenue and cost are the parameters
    profit = revenue - cost
    return profit # profit is the output

result = calculate_profit(150000, 120000)
print(result)

30000

In [104]:
def is_target_met(amount, target = 75000):
    return amount >= target
 
sales = [45000, 82000, 120000]
for amount in sales:
    print(amount, is_target_met(amount))

45000 False
82000 True
120000 True

In [105]:
def summarize(values):
    total = sum(values)
    average = total / len(values)
    return total, average
 
result = summarize([10, 20, 30])
print(result)

(60, 20.0)

In [111]:
# parameters, arguments, and return values
def calculate_margin(revenue, cost): # calculate_margin is a function
    profit = revenue - cost # revenue and cost are the parameters
    margin = profit / revenue * 100
    return margin

margin = calculate_margin(150000, 120000) # 150000, 120000 constitutes the argument

if margin >= 20:
    print("Healthy margin")

Healthy margin

In [4]:
sales = [45000, 82000, 120000, 67000, 95000]
target = 75000
# Your task:
# 1. Calculate total and average
# 2. Classify each value
# 3. Count values >= target
# 4. Use at least one function

In [7]:
def is_target_met(amount, target = 75000):
    return amount >= target

for index, amount in enumerate(sales):
    if is_target_met(amount):
        print(f"Value {index + 1}: PHP {amount:,.2f} (On-target)")
    else:
        print(f"Value {index + 1}: PHP {amount:,.2f} (Off-target)")

print(f"", end="\n")

average = sum(sales) / len(sales)

print(f"Total sales: PHP {sum(sales):,.2f}")
print(f"Average sales: PHP {average:,.2f}")
print(f"On-target count: {sum(x > 75000 for x in sales)}")

Value 1: PHP 45,000.00 (Off-target)
Value 2: PHP 82,000.00 (On-target)
Value 3: PHP 120,000.00 (On-target)
Value 4: PHP 67,000.00 (Off-target)
Value 5: PHP 95,000.00 (On-target)

Total sales: PHP 409,000.00
Average sales: PHP 81,800.00
On-target count: 3

In [1]:
import numpy as np
import pandas as pd
# Example use
values = np.array([10, 20, 30])
print(values)

[10 20 30]

In [2]:
np.__version__

'2.5.3'

In [3]:
pd.__version__

'3.0.6'

In [4]:
sales = np.array([45000, 82000, 120000])
print(sales)
print(sales * 1.05)

[ 45000  82000 120000]
[ 47250.  86100. 126000.]

In [20]:
grades = np.array([95, 92, 91, 88, 79, 89, 90])
average = np.average(grades)

In [21]:
print(average)

89.14285714285714

In [22]:
mean = np.mean(grades)
median = np.median(grades)

print(mean)
print(median)

89.14285714285714
90.0

In [23]:
from scipy import stats
mode = stats.mode(grades)
print(mode)

ModeResult(mode=np.int64(79), count=np.int64(1))

In [25]:
add_grades = grades + 3
print(add_grades)

[98 95 94 91 82 92 93]

In [26]:
prices = np.array([100, 200, 300, 400])
discounted = prices * 0.9

In [27]:
discounted

array([ 90., 180., 270., 360.])

In [28]:
std_dev = np.std(grades)

In [29]:
std_dev

np.float64(4.642307659791977)

In [31]:
grades_table = np.array([[80, 85], [90, 95], [75, 80]])

In [32]:
grades_table

array([[80, 85],
       [90, 95],
       [75, 80]])

In [34]:
grades_table[0][1]

np.int64(85)

In [35]:
print(grades_table[0][1])
print(grades_table[1][0])

85
90

In [36]:
sales = np.array([45000, 82000, 120000])
matrix = np.array([
[10, 20, 30],
[40, 50, 60]
])

print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

2
(2, 3)
6
int64

In [37]:
sales = np.array([45000, 82000, 120000, 67000, 95000])
print(sales[0]) # first
print(sales[-1]) # last
print(sales[1:4]) # slice
print(sales[sales >= 75000]) # Boolean filtering

45000
95000
[ 82000 120000  67000]
[ 82000 120000  95000]

In [38]:
matrix = np.array([
[10, 20, 30],
[40, 50, 60]
])

print(matrix[0, 1]) # 20
print(matrix[:, 1]) # second column

20
[20 50]

In [39]:
sales = np.array([45000, 82000, 120000, 67000, 95000])

print(sales * 1.05) # 5% increase
print(sales >= 75000) # Boolean mask
print(sales.sum())
print(sales.mean())
print(sales.min())
print(sales.max())
print(np.median(sales))

[ 47250.  86100. 126000.  70350.  99750.]
[False  True  True False  True]
409000
81800.0
45000
120000
82000.0

In [41]:
revenue = pd.Series([70000, 90000, 66000])

print(revenue)

0    70000
1    90000
2    66000
dtype: int64

In [43]:
data = {
'Region': ['North', 'South', 'North'],
'Product': ['Laptop', 'Phone', 'Tablet'],
'Revenue': [70000, 90000, 66000]
}
df = pd.DataFrame(data)

print(df)

  Region Product  Revenue
0  North  Laptop    70000
1  South   Phone    90000
2  North  Tablet    66000

In [50]:
customers = pd.read_csv('customers.csv')

In [49]:
customers

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9.755752e+09,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9.253268e+09,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9.218946e+09,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9.402610e+09,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,NaN,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver

In [53]:
orders = pd.read_csv('orders.csv')

In [54]:
orders

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73
...,...,...,...,...,...,...,...,...
15070,ORD0011300,CUST000701,2024-11-17 21:58:00,Cancelled,Marketplace,Express,0.036,75.40
15071,ORD0014948,CUST003808,28-Dec-2025 01:01,Completed,Mobile App,Standard,0.019,142.29
15072,ORD0012066,CUST004052,2025-05-04 06:07:00,Completed,Web,Standard,0.087,107.84
15073,ORD0012132,CUST002798,2025-04-29 21:11:00,Completed,Mobile App,Pickup,0.062,82.12
15074,ORD0013325,CUST001564,03/14/2024 04:48 PM,Completed,Marketplace,Standard,0.117,135.62

In [55]:
order_items = pd.read_csv('order_items.csv')

In [56]:
order_items

       order_item_id    order_id product_id  quantity unit_price_at_purchase
0      ITEM000000001  ORD0000001  PROD00513         2                 120.67
1      ITEM000000002  ORD0000002  PROD00124         2                  83.58
2      ITEM000000003  ORD0000002  PROD00631         2                  46.96
3      ITEM000000004  ORD0000002  PROD00136         1                 100.59
4      ITEM000000005  ORD0000002  PROD00090         1                 109.18
...              ...         ...        ...       ...                    ...
37758  ITEM000037216  ORD0014888  PROD00095         3                  48.27
37759  ITEM000028576  ORD0011406  PROD00702         1                  46.31
37760  ITEM000026308  ORD0010493  PROD00358         1                 130.84
37761  ITEM000020512  ORD0008174  PROD00075         3                  42.93
37762  ITEM000032925  ORD0013151  PROD00530         1                  106.4

[37763 rows x 5 columns]

In [57]:
customers.head(10)

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold
5,CUST000006,Jasmine,Reyes,Female,31.0,jasmine.reyes@companymail.ph,9.388497e+09,Region IV-A,CALABARZON,San Pablo,Brgy 6,2025-08-13,Gold
6,CUST000007,Juan,Diaz,F,18.0,juan.diaz@companymail.ph,9.691670e+09,Region IV-A,CALABARZON,Dasmariñas,Brgy 9,2025-10-22,Bronze
7,CUST000008,Leo,Navarro,Unknown,28.0,leo.navarro@companymail.ph,9.270483e+09,CARAGA,Caraga,Butuan,Brgy 2,2025-09-22,NaN
8,CUST000009,Kyle,Castillo,F,36.0,kyle.castillo@companymail.ph,9.957015e+09,Region III,Central Luzon,Olongapo,Brgy 10,2025-12-12,Bronze
9,CUST000010,Mia,Castillo,M,32.0,mia.castillo99@gmail.com,9.782490e+09,Region IV-A,CALABARZON,San Pablo,Brgy 2,2024-06-04,Gold

In [58]:
customers.size

65650

In [59]:
customers["last_name"].head(10)

0    DelosReyes
1         Ramos
2       Navarro
3        Rivera
4       Mendoza
5         Reyes
6          Diaz
7       Navarro
8      Castillo
9      Castillo
Name: last_name, dtype: str

In [60]:
customers[["last_name","first_name"]].head(10)

    last_name first_name
0  DelosReyes      Grace
1       Ramos        Ana
2     Navarro      Arvin
3      Rivera       Kyle
4     Mendoza       Juan
5       Reyes    Jasmine
6        Diaz       Juan
7     Navarro        Leo
8    Castillo       Kyle
9    Castillo        Mia

In [51]:
products = pd.read_csv('products.csv')

In [52]:
products

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [67]:
# "Electronics" is distinct from "electronics"
products[products["category"] == "Electronics"]

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
16,PROD00017,FitPro Electronics 378,FitPro,Electronics,60.05,₱109.58,117.0,pc,2022-10-17
20,PROD00021,FreshCart Electronics 722,FreshCart,Electronics,47.22,88.58,126.0,bottle,2024-04-24
23,PROD00024,NovaTech Electronics 485,NovaTech,Electronics,93.72,153.34,137.0,pack,2022-03-27
44,PROD00045,UrbanWear Electronics 232,UrbanWear,Electronics,15.95,21.3,96.0,pack,2022-03-03
64,PROD00065,FitPro Electronics 406,FitPro,Electronics,118.32,₱208.43,73.0,pcs,2022-07-27
...,...,...,...,...,...,...,...,...,...
765,PROD00766,BookNest Electronics 705,BookNest,Electronics,112.64,201.19,23.0,pcs,2022-10-12
768,PROD00769,HomeEase Electronics 838,HomeEase,Electronics,12.01,20.68,255.0,set,2023-03-09
773,PROD00774,NovaTech Electronics 253,NovaTech,Electronics,29.92,49.26,73.0,set,2024-08-13
781,PROD00782,GlowCo Electronics 922,GlowCo,Electronics,29.42,54.28,47.0,pack,2023-12-06
789,PROD00790,HomeEase Electronics 579,HomeEase,Electronics,116.25,208.61,154.0,pack,2024-06-04

In [75]:
products.dtypes

product_id          str
product_name        str
brand               str
category            str
unit_cost       float64
unit_price          str
stock_qty       float64
uom                 str
launch_date         str
dtype: object

In [76]:
products.describe()

        unit_cost   stock_qty
count  800.000000  781.000000
mean    60.889275  121.014085
std     30.585252   59.075645
min     10.000000    0.000000
25%     39.782500   81.000000
50%     54.345000  118.000000
75%     75.890000  162.000000
max    264.820000  322.000000

In [83]:
# loc vs. iloc
products.loc[0:2, ['product_id','product_name']]

  product_id           product_name
0  PROD00001      KidJoy Beauty 963
1  PROD00002      HomeEase Home 368
2  PROD00003  FreshCart Fashion 911

In [81]:
products.iloc[0:3, [0, 1]]

  product_id           product_name
0  PROD00001      KidJoy Beauty 963
1  PROD00002      HomeEase Home 368
2  PROD00003  FreshCart Fashion 911

In [86]:
mask = products['unit_cost'] >= 40
high_cost = products[mask]

In [87]:
high_cost

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
5,PROD00006,UrbanWear Toys 473,UrbanWear,Toys,120.33,225.17,120.0,bottle,2023-02-15
...,...,...,...,...,...,...,...,...,...
793,PROD00794,UrbanWear Beauty 461,UrbanWear,Beauty,46.56,61.54,186.0,set,2023-02-20
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [88]:
products[products['category'].isin(['Beauty','Fashion','Toys'])]

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
5,PROD00006,UrbanWear Toys 473,UrbanWear,Toys,120.33,225.17,120.0,bottle,2023-02-15
6,PROD00007,HomeEase Fashion 125,HomeEase,Fashion,57.48,97.28,NaN,pack,2023-08-26
...,...,...,...,...,...,...,...,...,...
779,PROD00780,KidJoy Beauty 583,KidJoy,Beauty,145.83,220.77,128.0,pcs,2024-09-11
787,PROD00788,UrbanWear Beauty 640,UrbanWear,Beauty,34.23,55.64,42.0,piece,2024-08-17
792,PROD00793,FreshCart Beauty 242,FreshCart,Beauty,24.24,40.13,114.0,pc,2022-11-22
793,PROD00794,UrbanWear Beauty 461,UrbanWear,Beauty,46.56,61.54,186.0,set,2023-02-20
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19

In [89]:
products[products['unit_cost'].between(35, 50)]

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
11,PROD00012,BookNest electronics 536,BookNest,electronics,45.86,68.12,186.0,piece,2024-06-03
...,...,...,...,...,...,...,...,...,...
766,PROD00767,FreshCart Beauty 268,FreshCart,Beauty,40.50,65.37,113.0,pc,2022-06-19
780,PROD00781,GlowCo Home 163,GlowCo,Home & Kitchen,41.99,71.06,51.0,pack,2023-03-30
782,PROD00783,Acme Books 505,Acme,Books,45.74,76.86,61.0,set,09/17/2023
788,PROD00789,NovaTech Groceries 153,NovaTech,Groceries,48.30,69.5,26.0,pcs,2022-08-05
793,PROD00794,UrbanWear Beauty 461,UrbanWear,Beauty,46.56,61.54,186.0,set,2023-02-20

In [90]:
customers

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9.755752e+09,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9.253268e+09,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9.218946e+09,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9.402610e+09,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,NaN,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver

In [91]:
customers[(customers['region_code'] == 'CARAGA') | (customers['region_code'] == 'NCR')]

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
7,CUST000008,Leo,Navarro,Unknown,28.0,leo.navarro@companymail.ph,9.270483e+09,CARAGA,Caraga,Butuan,Brgy 2,2025-09-22,NaN
13,CUST000014,Carlo,Castillo,M,39.0,carlo.castillo@gmail.com,9.810801e+09,CARAGA,Caraga,Bislig,Brgy 3,2025-05-13,Silver
15,CUST000016,Mark,Navarro,M,26.0,mark.navarro@gmail.com,9.812191e+09,NCR,Metro Manila,Taguig,Brgy 9,2023-07-09,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,CUST001217,Grace,Lopez,F,42.0,grace.lopez@mail.com,9.237338e+09,NCR,Metro Manila,Taguig,Brgy 6,2024-06-19,Bronze
5036,CUST002917,Grace,Navarro,F,20.0,grace.navarro13@companymail.ph,9.593411e+09,NCR,Metro Manila,Quezon City,Brgy 2,12-Sep-2024,Platinum
5040,CUST001514,Mark,Lopez,M,41.0,mark.lopez@mail.com,9.824979e+09,CARAGA,Caraga,Tandag,Brgy 9,2024-02-20,Bronze
5044,CUST004378,James,Aquino,F,36.0,james.aquino@gmail.com,9.037219e+09,CARAGA,Caraga,Tandag,Brgy 5,05/30/2025,Bronze
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,NaN,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver

In [93]:
customers_sorted = customers.sort_values('last_name', ascending = True)

In [94]:
customers_sorted

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
670,CUST000671,Ana,Aquino,F,39.0,ana.aquino@outlook.com,9.030103e+09,Region IV-A,CALABARZON,Dasmariñas,Brgy 2,2023-02-25,Bronze
1311,CUST001312,Leo,Aquino,Male,33.0,leo.aquino@mail.com,9.600128e+09,NCR,Metro Manila,Makati,Brgy 7,2024-06-05,Silver
4001,CUST004002,Ramon,Aquino,F,34.0,ramon.aquino@mail.com,9.488060e+09,Region III,Central Luzon,Olongapo,Brgy 6,2024-09-28,Gold
3995,CUST003996,Arvin,Aquino,Male,23.0,arvin.aquino90@mail.com,9.886136e+09,CARAGA,Caraga,Bislig,Brgy 8,2024-07-31,Gold
223,CUST000224,Mark,Aquino,NaN,30.0,mark.aquino@companymail.ph,9.033542e+09,NCR,Metro Manila,Quezon City,Brgy 9,2023-04-26,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3834,CUST003835,Ella,Villanueva,F,20.0,ella.villanueva@outlook.com,9.370477e+09,Region VII,Central Visayas,Mandaue,Brgy 6,2024-05-12,Bronze
1408,CUST001409,Kyle,Villanueva,Female,20.0,kyle.villanuevayahoo.com,9.762914e+09,Region IV-A,CALABARZON,Batangas City,Brgy 1,2024-08-19,Silver
4777,CUST004778,Maria,Villanueva,Unknown,29.0,maria.villanueva@yahoo.com,9.062012e+09,Region VII,Central Visayas,Cebu City,Brgy 1,2023-07-08,Bronze
2121,CUST002122,Noah,Villanueva,Male,21.0,noah.villanueva@yahoo.com,9.513564e+09,CARAGA,Caraga,Tandag,Brgy 7,2023-02-05,Bronze
1668,CUST001669,Leo,Villanueva,F,52.0,leo.villanueva@yahoo.com,NaN,CARAGA,Caraga,Tandag,Brgy 8,2023-07-29,Bronze

In [95]:
customers_sorted = customers.sort_values(['last_name', 'first_name'], ascending = [True, True])

In [96]:
customers_sorted

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
131,CUST000132,Ana,Aquino,Female,37.0,ana.aquino@outlook.com,9.047869e+09,Region III,Central Luzon,San Fernando,Brgy 2,2025-01-13,Silver
331,CUST000332,Ana,Aquino,M,44.0,ana.aquino23@outlook.com,9.499983e+09,Region III,Central Luzon,Olongapo,Brgy 10,2025-04-16,NaN
670,CUST000671,Ana,Aquino,F,39.0,ana.aquino@outlook.com,9.030103e+09,Region IV-A,CALABARZON,Dasmariñas,Brgy 2,2023-02-25,Bronze
908,CUST000909,Ana,Aquino,M,24.0,ana.aquino@outlook.com,9.643437e+09,Region IV-A,CALABARZON,Cavite City,Brgy 10,09/23/2024,Silver
1027,CUST001028,Ana,Aquino,M,22.0,ana.aquino7@outlook.com,9.056696e+09,Region III,Central Luzon,Olongapo,Brgy 1,2024-02-21,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3031,CUST003032,Ramon,Villanueva,M,20.0,ramon.villanueva@companymail.ph,9.657225e+09,CARAGA,Caraga,Tandag,Brgy 2,2023-04-14,NaN
3823,CUST003824,Ramon,Villanueva,M,28.0,ramon.villanueva@outlook.com,9.476601e+09,Region IV-A,CALABARZON,Calamba,Brgy 6,2023-11-03,Gold
4780,CUST004781,Ramon,Villanueva,M,NaN,ramon.villanueva@yahoo.com,9.593256e+09,Region IV-A,CALABARZON,San Pablo,Brgy 6,04/30/2024,Silver
4807,CUST004808,Ramon,Villanueva,Unknown,14.0,ramon.villanueva@outlook.com,9.519434e+09,Region VII,Central Visayas,Mandaue,Brgy 7,2026-01-07,Silver
5014,CUST003824,Ramon,Villanueva,M,28.0,ramon.villanueva@outlook.com,9.476601e+09,Region IV-A,CALABARZON,Calamba,Brgy 6,2023-11-03,Gold

In [97]:
customers.isna()

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,False,False,False,False,False,False,False,False,False,False,False,False,False
5046,False,False,False,False,False,False,False,False,False,False,False,False,False
5047,False,False,False,False,False,False,False,False,False,False,False,False,False
5048,False,False,False,False,False,False,False,False,False,False,False,False,False
5049,False,False,False,False,False,False,True,False,False,False,False,False,False

In [98]:
customers.isna().sum()

customer_id       0
first_name        0
last_name         0
gender          301
age             150
email           107
phone           147
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
loyalty_tier    266
dtype: int64

In [99]:
products['unit_cost'].sum()

np.float64(48711.42)

In [100]:
products['unit_cost'].count()

np.int64(800)

In [103]:
customers['email'].count()

np.int64(4943)

In [104]:
customers['email'].nunique()

3360

In [105]:
total_cost_by_category = (
    products.groupby('category')['unit_cost']
    .sum()
    .sort_values(ascending = True)
)

In [106]:
total_cost_by_category

category
Sports & Outdoor     531.67
Fashon               595.36
Beauty & Care        693.84
Toy                  696.54
Grocery              749.86
Electronics          829.72
Elec                 883.01
Book                1125.59
electronics         1247.61
Home and Kitchen    1267.03
Electronics         3859.67
Groceries           4676.05
Sports              4808.82
Home & Kitchen      4870.78
Books               4905.09
Beauty              5419.52
Fashion             5610.20
Toys                5941.06
Name: unit_cost, dtype: float64

In [107]:
multiple_aggregation_by_category = (
    products.groupby('category')
        .agg(
            unit_cost_sum = ('unit_cost', 'sum'),
            stock_qty_sum = ('stock_qty', 'sum'),
            unit_cost_min = ('unit_cost', 'min'),
            unit_cost_max = ('unit_cost', 'max'),
            unit_cost_mean = ('unit_cost', 'mean')
        )
        .reset_index()
)

In [108]:
multiple_aggregation_by_category

,category,unit_cost_sum,stock_qty_sum,unit_cost_min,unit_cost_max,unit_cost_mean
0,Beauty,5419.52,10773.0,10.00,149.16,57.654468
1,Beauty & Care,693.84,1446.0,45.76,86.68,63.076364
2,Book,1125.59,2359.0,25.58,111.33,56.279500
3,Books,4905.09,9838.0,19.71,120.14,54.501000
4,Elec,883.01,1315.0,32.94,147.74,80.273636
5,Electronics,3859.67,7827.0,12.01,181.22,54.361549
6,Electronics,829.72,1929.0,16.84,94.80,48.807059
7,Fashion,5610.20,11690.0,20.56,201.14,63.035955
8,Fashon,595.36,940.0,18.61,124.74,74.420000
9,Groceries,4676.05,9337.0,10.99,127.39,60.727922
10,Grocery,749.86,1599.0,20.66,110.76,62.488333
11,Home & Kitchen,4870.78,8788.0,18.11,162.89,64.089211
12,Home and Kitchen,1267.03,2596.0,26.62,192.76,66.685789
13,Sports,4808.82,8902.0,16.82,135.12,64.984054
14,Sports & Outdoor,531.67,1041.0,35.75,119.74,66.458750
15,Toy,696.54,1406.0,30.66,107.90,63.321818
16,Toys,5941.06,10468.0,19.22,264.82,64.576739
17,electronics,1247.61,2258.0,25.44,118.75,62.380500

In [101]:
# Retrieve the amount paid > 1500 and payment method via GCash and PayMaya
# Sort the amount paid from highest to lowest
# Calculate the amount paid (total, average, minimum, and maximum)
# Group the total amount paid by payment method
# Write at least three findings in plain language

import numpy as np
import pandas as pd

In [102]:
payments = pd.read_csv('payments.csv')

In [103]:
payments

,payment_id,order_id,payment_method,payment_status,payment_date,amount_paid
0,PAY0000001,ORD0000001,GCash,Paid,2024-05-09,2822.72
1,PAY0000002,ORD0000002,COD,Paid,06/25/2024,2499.76
2,PAY0000003,ORD0000003,GCash,Paid,2025-06-10,1983.66
3,PAY0000004,ORD0000004,PayMaya,Failed,2025-06-21,1765.99
4,PAY0000005,ORD0000005,COD,Pending,06/28/2024,1477.53
...,...,...,...,...,...,...
14995,PAY0014996,ORD0014996,GCash,Paid,2025-06-07,1985.86
14996,PAY0014997,ORD0014997,PayMaya,Paid,2025-12-03,1596.22
14997,PAY0014998,ORD0014998,Bank Transfer,Paid,2026-01-05,836.13
14998,PAY0014999,ORD0014999,GCash,Paid,12/19/2025,NaN
14999,PAY0015000,ORD0015000,GCash,Paid,2025-12-14,2227.32

In [104]:
# Retrieve the amount paid > 1500 and payment method via GCash and PayMaya
# Sort the amount paid from highest to lowest

payments_sorted = payments[
    (pd.to_numeric(payments['amount_paid'], errors = 'coerce') > 1500) & 
    ((payments['payment_method'] == 'GCash') | 
    (payments['payment_method'] == 'PayMaya'))
].sort_values('amount_paid', ascending = False)

In [105]:
payments_sorted

,payment_id,order_id,payment_method,payment_status,payment_date,amount_paid
11392,PAY0011393,ORD0011393,PayMaya,Paid,2025-07-08,5525.51
9819,PAY0009820,ORD0009820,PayMaya,Paid,2024-05-29,4373.93
4955,PAY0004956,ORD0004956,GCash,Paid,2025-02-19,4251.38
5147,PAY0005148,ORD0005148,GCash,Paid,2024-06-30,4182.22
3867,PAY0003868,ORD0003868,GCash,Failed,2025-06-13,3991.49
...,...,...,...,...,...,...
1527,PAY0001528,ORD0001528,PayMaya,Paid,06/29/2025,1500.99
4102,PAY0004103,ORD0004103,GCash,Paid,2024-08-30,1500.97
8782,PAY0008783,ORD0008783,PayMaya,Refunded,2025-08-27,1500.94
4885,PAY0004886,ORD0004886,PayMaya,Paid,2024-02-15,1500.47
5420,PAY0005421,ORD0005421,GCash,Paid,2025-10-04,1500.28

In [106]:
# Calculate the amount paid (total, average, minimum, and maximum)
# Group the total amount paid by payment method

payments_sorted['amount_paid'] = pd.to_numeric(
    payments_sorted['amount_paid'],
    errors = 'coerce'
)

payments_aggregation = (
    payments_sorted.groupby('payment_method')
        .agg(
            amount_paid_sum = ('amount_paid', 'sum'),
            amount_paid_mean = ('amount_paid', 'mean'),
            amount_paid_min = ('amount_paid', 'min'),
            amount_paid_max = ('amount_paid', 'max')
        )
        .reset_index()
)

In [107]:
payments_aggregation

,payment_method,amount_paid_sum,amount_paid_mean,amount_paid_min,amount_paid_max
0,GCash,2914008.07,2200.912440,1500.28,4251.38
1,PayMaya,2949127.11,2191.030542,1500.47,5525.51

In [108]:
# Write at least three findings in plain language

amount_paid_sum_GCash = payments_aggregation.iloc[0]['amount_paid_sum']
amount_paid_sum_PayMaya = payments_aggregation.iloc[1]['amount_paid_sum']

amount_paid_mean_GCash = payments_aggregation.iloc[0]['amount_paid_mean']
amount_paid_mean_PayMaya = payments_aggregation.iloc[1]['amount_paid_mean']

amount_paid_min_GCash = payments_aggregation.iloc[0]['amount_paid_min']
amount_paid_min_PayMaya = payments_aggregation.iloc[1]['amount_paid_min']

amount_paid_max_GCash = payments_aggregation.iloc[0]['amount_paid_max']
amount_paid_max_PayMaya = payments_aggregation.iloc[1]['amount_paid_max']

print(f"In terms of the amount paid exceeding PHP 1,500.00:", end = "\n")

print(f"• PayMaya registered a sum amounting to PHP {amount_paid_sum_PayMaya:,.2f} — exceeding that of GCash amounting to PHP {amount_paid_sum_GCash:,.2f}.", end = "\n")

print(f"• GCash registered a mean amounting to PHP {amount_paid_mean_GCash:,.2f} — exceeding that of PayMaya amounting to PHP {amount_paid_mean_PayMaya:,.2f}.", end = "\n")

print(f"• PayMaya received payments ranging from PHP {amount_paid_min_PayMaya:,.2f} to {amount_paid_max_PayMaya:,.2f} — varying more than those of GCash ranging from PHP {amount_paid_min_GCash:,.2f} to {amount_paid_max_GCash:,.2f}.")

In terms of the amount paid exceeding PHP 1,500.00:
• PayMaya registered a sum amounting to PHP 2,949,127.11 — exceeding that of GCash amounting to PHP 2,914,008.07.
• GCash registered a mean amounting to PHP 2,200.91 — exceeding that of PayMaya amounting to PHP 2,191.03.
• PayMaya received payments ranging from PHP 1,500.47 to 5,525.51 — varying more than those of GCash ranging from PHP 1,500.28 to 4,251.38.